export const Cars = [
  {
    id: '1',
    name: 'BMW 4 серия',
    brand: 'BMW',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9',
    type: 'Купе',
    seats: 4,
    transmission: 'Автоматическая',
    fuelType: 'Бензин',
    available: true,
  },
  {
    id: '2',
    name: 'Explorer',
    brand: 'Ford',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf',
    type: 'Внедорожник',
    seats: 7,
    transmission: 'Механическая',
    fuelType: 'Бензин',
    available: true,
  },
  {
    id: '3',
    name: 'MINI Couper Clubman',
    brand: 'MINI',
    price: 3000,
    image: 'https://images.unsplash.com/photo-1617624085810-3df2165bd11b',
    type: 'Внедорожник',
    seats: 5,
    transmission: 'Автоматическая',
    fuelType: 'Бензин',
    available: true,
  },
  {
    id: '4',
    name: 'Model 3',
    brand: 'Tesla',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1536700503339-1e4b06520771',
    type: 'Седан',
    seats: 5,
    transmission: 'Автоматическая',
    fuelType: 'Электро',
    available: true,
  },
  {
    id: '5',
    name: 'Cayenne',
    brand: 'Porsche',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70',
    type: 'Внедорожник',
    seats: 5,
    transmission: 'Автоматическая',
    fuelType: 'Бензин',
    available: true,
  },
  {
    id: '6',
    name: 'A-Class',
    brand: 'Mercedes-Benz',
    price: 3800,
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8',
    type: 'Хэтчбек',
    seats: 5,
    transmission: 'Автоматическая',
    fuelType: 'Бензин',
    available: true,
  }
];